# Generated by Django 4.1.7 on 2024-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_users_chat_messageuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_application',
            name='picture',
            field=models.ImageField(default='default_pictrute-chat.png', upload_to='static/chat/images/avatarki_chat/', verbose_name="chat's avatarka"),
        ),
    ]
