# Generated by Django 4.1.7 on 2024-01-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_users_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_application',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
