# Generated by Django 4.1.7 on 2023-11-24 15:29

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=40, verbose_name="person's first name")),
                ('last_name', models.CharField(max_length=40, verbose_name="person's last name")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=40, unique=True, verbose_name="person's username")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name="person's email")),
                ('password', models.CharField(max_length=40, verbose_name="person's password")),
                ('profile_picture', models.ImageField(default='avatarka_default.png', upload_to='static/user_app/images/avatarki/', verbose_name="person's avatarka")),
                ('quotation', models.CharField(max_length=150, verbose_name="person's quotation")),
                ('data_birn', models.DateField(unique=True, verbose_name="person's data birn")),
                ('DataCreateUser', models.DateField(auto_now=True, verbose_name="person's data create account")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
