# Generated by Django 4.1.7 on 2023-11-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=70, verbose_name="person's first name"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name="person's last name"),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=70, verbose_name="person's password"),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=70, unique=True, verbose_name="person's username"),
        ),
    ]
