# Generated by Django 4.1.7 on 2023-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_birn',
            field=models.DateField(auto_now=True, verbose_name="person's data birn"),
        ),
    ]
