# Generated by Django 4.1.7 on 2023-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_user_data_birn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_birn',
            field=models.DateField(default='2000-1-1', verbose_name="person's data birn"),
        ),
    ]
