# Generated by Django 4.1.7 on 2023-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_user_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=True, verbose_name="person's online"),
        ),
    ]
